import { Contract, Interface, VoidSigner } from './contracts';
import * as providers from './providers';
import { HDNode, SigningKey, Wallet } from './wallet';
import { AbiCoder } from './utils/abi-coder';
import { BigNumber } from './utils/bignumber';
import * as constants from './utils/constants';
import * as errors from './utils/errors';
import * as utils from './utils';
import * as types from './types';
import * as wordlists from './wordlists';
import { platform } from './utils/shims';
import { version } from './_version';
declare function getDefaultProvider(network?: types.Network | string): providers.BaseProvider;
export { Wallet, VoidSigner, HDNode, SigningKey, Contract, Interface, getDefaultProvider, providers, AbiCoder, BigNumber, errors, constants, utils, types, wordlists, platform, version };
