name: Beta (v6) Bug
description: Open an issue for a bug in the v6 beta
title: "Title Here"
labels: ["v6-beta"]
assignees:
  - ricmoo
body:
  - type: markdown
    attributes:
      value: |
        This form is **only** for issues in the **v6 beta**, which you can access using either the `v6-beta` tag in the repository or install using `ethers@beta` with `npm`.

        The v6 branch will be very lively, undergoing a lot of changes, including backwards compatible changes between beta versions.

        Before opening an issue, please make sure you have **fully updated to the latest version** by removing the `node_modules/` and `package-lock.json` and then running a fresh `npm install`. Otherwise you may end up with incompatible versions which may conflict with each other.

        Thanks for trying out the v6 beta! Cheers!
  - type: input
    id: version
    attributes:
      label: Ethers Beta Version
      description: What version of ethers are you using? Before opening an issue, please make sure you are using the latest beta.
      placeholder: x.y.z-beta.N
    validations:
      required: true
  - type: textarea
    id: about-the-bug
    attributes:
      label: Describe the Problem
      description: Please describe what you expected to happen vs what did happen?
      placeholder: What happened?
    validations:
      required: true
  - type: textarea
    id: code-snippet
    attributes:
      label: Code Snippet
      description: If possible, please include a **short and concise** code snippets that can reproduce this issue. Ideally code that can be pasted into the [Ethers Playground](https://playground.ethers.org).
      placeholder: e.g. provider.getBlockNumber()
      render: shell
  - type: textarea
    id: errors
    attributes:
      label: Errors
      description: If there is an error, please include the **entire error** (redacting any sensitive information).
      placeholder: "e.g. Error: invalid name (code='INVALID_ARGUMENT, ...)"
      render: shell
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment, platforms or frameworks are you using? Select all that apply.
      multiple: true
      options:
        - node.js
        - Browser (Chrome, Safari, etc)
        - React Native/Expo/JavaScriptCore
        - Hardhat
        - Geth
        - Parity
        - Ganache
        - Other (please specify)
  - type: input
    id: other-envrionment
    attributes:
      label: Environment (Other)
      placeholder: anything else?
