import { Wordlist } from '../utils/wordlist';
declare const en: Wordlist;
declare const es: Wordlist;
declare const fr: Wordlist;
declare const it: Wordlist;
declare const ja: Wordlist;
declare const ko: Wordlist;
declare const zh: Wordlist;
declare const zh_cn: Wordlist;
declare const zh_tw: Wordlist;
export { en, es, fr, it, ja, ko, zh, zh_cn, zh_tw };
