"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var lang_ja_1 = require("./lang-ja");
var lang_ko_1 = require("./lang-ko");
var lang_it_1 = require("./lang-it");
var lang_en_1 = require("./lang-en");
var lang_zh_1 = require("./lang-zh");
var en = lang_en_1.langEn;
exports.en = en;
var ko = lang_ko_1.langKo;
exports.ko = ko;
var it = lang_it_1.langIt;
exports.it = it;
var ja = lang_ja_1.langJa;
exports.ja = ja;
var zh = lang_zh_1.langZhCn;
exports.zh = zh;
var zh_cn = lang_zh_1.langZhCn;
exports.zh_cn = zh_cn;
var zh_tw = lang_zh_1.langZhTw;
exports.zh_tw = zh_tw;
