declare const ethers: any;
declare const data: string[];
declare const mapping: {
    A: number;
    B: number;
    C: number;
    D: number;
    E: number;
    F: number;
    G: number;
    H: number;
    I: number;
    J: number;
    K: number;
    L: number;
    M: number;
    N: number;
    O: number;
    P: number;
    Q: number;
    R: number;
    S: number;
    T: number;
    U: number;
    V: number;
    W: number;
    X: number;
    Y: number;
    Z: number;
    a: number;
    b: number;
    c: number;
    d: number;
    e: number;
    f: number;
    g: number;
    h: number;
    i: number;
    j: number;
    k: number;
    l: number;
    m: number;
    n: number;
    o: number;
    p: number;
    q: number;
    r: number;
    s: number;
    t: number;
    u: number;
    v: number;
    w: number;
    x: number;
    y: number;
    z: number;
};
declare var transform: {};
declare function normalize(word: any): string;
declare function sortJapanese(a: any, b: any): 0 | 1 | -1;
declare let words: any[];
declare let kyoku: any;
declare function getWord(index: any): any;
declare function getWordIndex(word: any): number;
